### ISSUE TITLE
Holes in thin spots

### ISSUE THREAD

**Issue by brocktice** [SCIInstitute/Cleaver2#54]
I have a mask that another meshing package can handle without introducing holes. However, Cleaver2 is introducing holes in the thin spots.

Unfortunately I don't know enough about the meshing technique to understand the effects of the parameters, but it seems like the alpha and sigma parameters may have an effect.

What can I do to avoid these holes? I tried increasing resolution by decreasing scaling factor, but that didn't help.

**Comment by jonbronson** [comment]
Cleaver works by sampling a background lattice and computing where interfaces intersect with that background lattice. A series of topological changes to the mesh occur along those interfaces to guarantee element quality. Thin features can be problematic when they only span a single background cell, because those topological operations to enforce element quality can cause pinch the two material interfaces together.

Modifying the scaling factor will change how many samples of the input volume appear on the background mesh. Using fewer samples will increase the likelihood that holes are introduced into the mesh, as it will increase the number of thin regions as well as regions which are not capturable at low sampling rates. Increasing the scaling factor will increase the number of samples on the background lattice and decrease the changes of a thin region producing holes. It will also create more elements in the output mesh.
