### ISSUE TITLE
Sizing Field: Bug -- export causes crashing

### ISSUE THREAD

**Issue by zaracay** [SCIInstitute/Cleaver2#58]
At closing, Cleaver asks to save out the sizing field.  Clicking save causes Cleaver to crash.

**Comment by jonbronson** [comment]
Fixed in commit. 3c0bf9a674d68517172fc106f6425eb3691b062f

This issue occurred on MacOS because the system overrides Qt's file save dialog with a system native dialog that does not support default file types. The ITK file save library call also requires the .nrrd extension to be there, or it throws an exception. New Cleaver behavior is to explicitly add the .nrrd extension to the filename.
